server:
  port: 8186

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:55000/ecommerce_order
    username: postgres
    password: postgrespw
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true